# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pencarian.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import login
import register
import pembayaran
import konfirmasiSupir
import ulasan
import registerKendaraan
import pembayaran
class pencarian(object):
    def loadData(self):
        result=[]
        self.database.getData("select IDKend,namakendaraan,tahun,alamat,harga,deskripsi,tambahan from kendaraan",result)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
    def openWindowUlasan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ulasan.ulasan()
        self.ui.setupUi(self.window,self.username,self.database)
        self.window.show()
        self.MainWindow.close()
    def openWindowRegisterKendaraan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = registerKendaraan.registerKendaraan()
        self.ui.setupUi(self.window,self.username,self.database)
        self.window.show()
        self.MainWindow.close()
    def openWindowPembayaran(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = pembayaran.pembayaran()
        self.ui.setupUi(self.window,self.username,self.database)
        self.window.show()
        self.MainWindow.close()
    def openWindowLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = login.login()
        self.ui.setupUi(self.window,self.database)
        self.window.show()
        self.MainWindow.close()
    def openWindowRegister(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = register.register()
        self.ui.setupUi(self.window,self.database)
        self.window.show()
        self.MainWindow.close()
    def openWindowKonfirmasiSupir(self):
        self.dialog = QtWidgets.QDialog()
        self.ui = konfirmasiSupir.konfirmasiSupir()
        self.ui.setupUi(self.dialog,self.mobil,self.database,self.username)
        self.dialog.show()
        self.MainWindow.close()
    def messageBox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    def pushKonfirmasiSupir(self):
        self.openWindowKonfirmasiSupir()
    def pushLogin(self):
        self.openWindowLogin()
    def pushSignUp(self):
        self.openWindowRegister()
    def click_on_table(self,item):
        self.mobil=item.text()
    def handleButton(self):
        nama=self.lineEdit.text()
        self.tableWidget.clearContents()
        result=[]
        self.database.getData("select IDKend,namakendaraan,tahun,alamat,harga,deskripsi,tambahan from kendaraan where namakendaraan LIKE '{}%'".format(nama),result)
        self.tableWidget.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
    def setupUi(self, MainWindow, username, database):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 789, 343))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_3.clicked.connect(self.pushLogin)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton.clicked.connect(self.pushSignUp)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.pushButton_5.clicked.connect(self.handleButton)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.tableWidget.itemClicked.connect(self.click_on_table)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_2.clicked.connect(self.pushKonfirmasiSupir)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setFamily("Segoe UI Semilight")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(40, 510, 211, 51))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.clicked.connect(self.openWindowPembayaran)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(220, 510, 221, 51))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.clicked.connect(self.openWindowRegisterKendaraan)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(620, 510, 221, 51))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_3.setFont(font)
        self.commandLinkButton_3.clicked.connect(self.openWindowUlasan)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(440, 510, 221, 51))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_4.setFont(font)
        self.commandLinkButton_4.clicked.connect(self.openWindowLogin)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.MainWindow=MainWindow 
        self.username=username
        self.database= database
        self.loadData()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pinjam.in"))
        self.pushButton_3.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Signed in as User"))
        self.lineEdit.setText(_translate("MainWindow", "Cari Nama Kendaraan"))
        self.pushButton_5.setText(_translate("MainWindow", "CARI"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Kendaraan"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tahun"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Alamat"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Harga"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Deskripsi"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Harga Tambahan Supir"))
        self.pushButton_2.setText(_translate("MainWindow", "PINJAM"))
        self.commandLinkButton.setText(_translate("MainWindow", "pembayaran"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "registrasi kendaraan"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "ulasan"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "log out"))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = pencarian()
    ui.setupUi(MainWindow,"aaaaa")
    MainWindow.show()
    sys.exit(app.exec_())
'''
